### ISSUE TITLE
Replace flake8 with ruff

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/variation-normalization#475]
Side note: this repo is getting pretty big -- that would make it a good candidate for [Ruff](https://github.com/astral-sh/ruff) imo. Not sure how flake8/etc checks feel in others' editors but flake8 alone is taking me almost 5 seconds to cover `variation/` and `tests/` whereas Ruff is almost instant.

**Comment by jsstevenson** [comment]
...and, as I keep reading, it looks like this should be addressed in #474

**Comment by korikuzma** [comment]
I added it in #474 but it wasn’t getting everything. I was wondering why sometimes flake8 (both GH actions and local) wouldn’t catch missing docstrings. Flake8 passed locally on my machine, so I’ll switch to ruff in #474.

**Comment by korikuzma** [comment]
The annotation warnings we ignore in flake8. It looks like we do this in therapy but not disease/gene

**Comment by korikuzma** [comment]
@jsstevenson this is what i have in my `ruff.toml`. Let me know if I should modify

```toml
select = ["E", "W", "F", "ANN", "Q", "D"]

line-length = 88

ignore = ["D205", "D400", "D415", "ANN101"]

[flake8-quotes]
inline-quotes = "double"

[per-file-ignores]
"tests/*" = ["ANN001", "ANN2", "ANN102"]
"setup.py" = ["F821"]
"*__init__.py" = ["F401"]
```
