### ISSUE TITLE
Update metaschema to use VRS 2.0-alpha changes

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/variation-normalization#476]
Will do this once #474 gets merged and VRS-Python has been updated to use pydantic V2 models

**Comment by korikuzma** [comment]
We're going to break this up into two parts:
- [ ] Pull in refactor changes
- [ ] Pull in vrs-python updated pydantic models

**Comment by korikuzma** [comment]
Per @ahwagner HGVS Dup Del Mode will be updated to:

```markdown
This mode helps us interpret deletions and duplications that are represented as HGVS expressions.\
The mode can be set to `default`, `copy_number_count`, `copy_number_change`, `ref_len_expr`, or `literal_seq_expr`.


## Default Characteristics

- if baseline_copies is not set and endpoints are ambiguous:
    - copy_number_change
    - if copy_change not provided:
        - copy_change = `efo:0030067` (loss) if del, `efo:0030070` (gain) if dup
- elif baseline_copies is provided:
    - copy_number_count
    - copies are baseline_copies + 1 for dup, baseline_copies - 1 for del
- elif len dup > 100bp: (use outermost coordinates)
    - ref_len_expr (Allele)
      - state.length is 0 if deletion
- else:
    - literal_seq_expr (normalized LiteralSequenceExpression Allele)
```

`1000_2000dup` (assuming inter-residue) will be represented as:

```json
{
  "type": "Allele",
  "location": {
    "sequence": "refseq:1",
    "start": 1000,
    "end": 2000
  },
  "state": {
    "type": "ReferenceLengthExpression",
    "length": 2000,
    "repeatSubunitLength": 1000
  }
}
```


`1000_2000del` (assuming inter-residue) will be represented as:

```json
{
  "type": "Allele",
  "location": {
    "sequence": "refseq:1",
    "start": 1000,
    "end": 2000
  },
  "state": {
    "type": "ReferenceLengthExpression",
    "length": 0,
    "repeatSubunitLength": 1000
  }
}
```

**Comment by korikuzma** [comment]
Per @ahwagner , we are going to change the HGVS Dup Del Modes to `copy_number_count`, `copy_number_change` and `allele`. We are also going to parameterize the sequence length returned in an Allele in #481 . Since [this](https://github.com/ga4gh/vrs-python/pull/234) PR in vrs-python provides a cut off limit, we will use that for now until we get to #481

**Comment by korikuzma** [comment]
> Per @ahwagner , we are going to change the HGVS Dup Del Modes to `copy_number_count`, `copy_number_change` and `allele`. We are also going to parameterize the sequence length returned in an Allele in #481 . Since [this](https://github.com/ga4gh/vrs-python/pull/234) PR in vrs-python provides a cut off limit, we will use that for now until we get to #481

@ahwagner For `allele`, should the starting allele (before running through vrs-python's `_normalize_allele` function) be represented as an Allele with LSE or RLE? Here's my proposal:

```yaml
if len dup > 100bp: (use outermost coordinates)
    - ref_len_expr
        - state.repeatSubunitLength
            - deletion: length of alt sequence
            - duplication: location.end - location.start
        - state.length
            - deletion: 0
            - duplication: state.repeatSubunitLength * 2
else:
    - literal_seq_expr
```
